package mods.tesseract.mycelium;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.client.event.DrawBlockHighlightEvent;
import net.minecraftforge.client.event.RenderBlockOverlayEvent;
import net.minecraftforge.common.MinecraftForge;

import java.util.Collections;

@Mod(modid = ForgeMod.MODID, useMetadata = true, version = ForgeMod.VERSION, name = ForgeMod.NAME)
public class ForgeMod {
    public static final String MODID = "mycelium";
    public static final String NAME = "Mycelium";
    public static final String VERSION = "1.5.11";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        MinecraftForge.EVENT_BUS.register(this);
        e.getModMetadata().autogenerated = false;

        e.getModMetadata().name = ForgeMod.NAME;
        e.getModMetadata().version = ForgeMod.VERSION;
        e.getModMetadata().credits = "Matrix (TCLProject) , HRudyPlayZ";

        Collections.addAll(e.getModMetadata().authorList, "Tesseract");

        e.getModMetadata().url = "";

        e.getModMetadata().description = "A library mod used for multiple things including easy ASM fixes and more.";

        e.getModMetadata().logoFile = "assets/" + ForgeMod.MODID + "/logo.png";
    }

    @SubscribeEvent
    public void onRenderBlockOverlay(RenderBlockOverlayEvent e) {
        if (e.player.noClip)
            e.setCanceled(true);
    }

    @SubscribeEvent
    public void onBlockHighlight(DrawBlockHighlightEvent e) {
        if (e.player.isEntityInsideOpaqueBlock())
            e.setCanceled(true);
    }
}
