package cn.tesseract.mycelium;

import cn.tesseract.mycelium.asm.minecraft.HookLoader;
import cn.tesseract.mycelium.asm.minecraft.PrimaryClassTransformer;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.common.MinecraftForge;

import java.util.Collections;

@Mod(modid = Mycelium.MODID, useMetadata = true, version = Mycelium.VERSION, name = Mycelium.NAME)
public class Mycelium {
    public static final String MODID = "mycelium";
    public static final String NAME = "Mycelium";
    public static final String VERSION = "2.0";

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        MinecraftForge.EVENT_BUS.register(this);
        e.getModMetadata().autogenerated = false;

        e.getModMetadata().name = Mycelium.NAME;
        e.getModMetadata().version = Mycelium.VERSION;
        e.getModMetadata().credits = "Gloomy Folken";

        Collections.addAll(e.getModMetadata().authorList, "Tesseract");

        e.getModMetadata().url = "";

        e.getModMetadata().description = "A library mod used for multiple things including easy ASM fixes and more.";
    }
}

