package net.tclproject.mysteriumlib;

import net.minecraft.launchwrapper.Launch;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.util.Collections;

@Mod(modid = Tags.MODID, useMetadata = true, version = Tags.VERSION, name = Tags.NAME)
public class ForgeMod {
    @Mod.Instance(Tags.MODID)
    public static ForgeMod instance;

    private boolean obfuscated;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        makeFancyModInfo(event);

        instance = this;
        MinecraftForge.EVENT_BUS.register(instance);
    }

    public void makeFancyModInfo(FMLPreInitializationEvent event) {
        // The following will overwrite the mcmod.info file so the info page looks good.
        // Adapted from Jabelar's Magic Beans and AstroTibs's OptionsEnforcer.

        // This will stop Forge from complaining about missing mcmod.info (just in case i forget it).
        event.getModMetadata().autogenerated = false;

        event.getModMetadata().name = Tags.NAME; // Mod name
        event.getModMetadata().version = Tags.VERSION; // Mod version
        event.getModMetadata().credits = "Matrix (TCLProject) , HRudyPlayZ"; // Mod credits

        // Author list
        event.getModMetadata().authorList.clear();
        Collections.addAll(event.getModMetadata().authorList, "Tesseract");

        // Mod description
        event.getModMetadata().description = "A library mod used for multiple things including easy ASM fixes and more.";
        event.getModMetadata().logoFile = "assets/" + Tags.MODID + "/logo.png"; // Mod logo
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        this.obfuscated = !(Boolean) Launch.blackboard.get("fml.deobfuscatedEnvironment");
    }
}
